// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWIKDZJgBumjxjYdRw4SAWtnLmkY4FkDI',
    appId: '1:690859868698:web:e3b2dc8b19f48940b187a3',
    messagingSenderId: '690859868698',
    projectId: 'banking-app-7c21d',
    authDomain: 'banking-app-7c21d.firebaseapp.com',
    storageBucket: 'banking-app-7c21d.firebasestorage.app',
    measurementId: 'G-G6VZR9VL65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWIKDZJgBumjxjYdRw4SAWtnLmkY4FkDI',
    appId: '1:690859868698:android:PLACEHOLDER',
    messagingSenderId: '690859868698',
    projectId: 'banking-app-7c21d',
    storageBucket: 'banking-app-7c21d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWIKDZJgBumjxjYdRw4SAWtnLmkY4FkDI',
    appId: '1:690859868698:ios:PLACEHOLDER',
    messagingSenderId: '690859868698',
    projectId: 'banking-app-7c21d',
    storageBucket: 'banking-app-7c21d.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWIKDZJgBumjxjYdRw4SAWtnLmkY4FkDI',
    appId: '1:690859868698:macos:PLACEHOLDER',
    messagingSenderId: '690859868698',
    projectId: 'banking-app-7c21d',
    storageBucket: 'banking-app-7c21d.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWIKDZJgBumjxjYdRw4SAWtnLmkY4FkDI',
    appId: '1:690859868698:windows:PLACEHOLDER',
    messagingSenderId: '690859868698',
    projectId: 'banking-app-7c21d',
    authDomain: 'banking-app-7c21d.firebaseapp.com',
    storageBucket: 'banking-app-7c21d.firebasestorage.app',
  );
}
